name: kakeibo-app

services:
  # 1. データベース (PostgreSQL)
  db:
    image: postgres:15
    container_name: kakeibo-db
    environment:
      POSTGRES_DB: kakeibo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # 3. フロントエンド (Next.js)
  frontend:
    build:
      context: ./kakeibo-frontend # Next.jsのDockerfileがあるフォルダパス
    container_name: kakeibo-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

# データベースのデータをPC内に永続保存するための設定
volumes:
  db_data: