spring.application.name=kakeibo-backend

# DB接続情報
spring.datasource.url=jdbc:postgresql://localhost:5432/kakeibo_db
spring.datasource.username=postgres
spring.datasource.password=password


# 1. 実行されたSQLをログに出力する
spring.jpa.show-sql=true

# 2. 出力されるSQLを見やすく整形（フォーマット）する
spring.jpa.properties.hibernate.format_sql=true

# 3. SQLの「?」に入った具体的なパラメータ（バインド変数）の値をログに出す
logging.level.org.hibernate.orm.jdbc.bind=trace

# データベース接続が失敗したとき、あきらめずにリトライする設定
spring.datasource.hikari.initialization-fail-timeout=30000